routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return redirect()->route('company.index');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('company', CompanyController::class)->except(['show']);
Route::get('company/{company}/employees', 'App\Http\Controllers\CompanyController@employees')->name('company.employees');
Route::get('company/{company}/employee/create', 'App\Http\Controllers\EmployeeController@create')->name('company.employee.create');
Route::resource('employee', EmployeeController::class)->except(['show']);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/company-create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            <span class="text-gray-800">{{ __('Create company') }}</span>
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-1 gap-6">
                        <form method="post" action="{{ @route('company.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('partials.company-form')
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/company-edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            <span class="text-gray-800">{{ $company->name }}</span><i class="fa fa-edit text-gray-400 ml-2"></i>
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-1 gap-6">
                        <form method="post" action="{{ @route('company.update', $company->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            @include('partials.company-form')
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/company.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Companies') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ @route('company.create') }}" class="float-right">
                        <i class="fa fa-plus-circle"></i>
                    </a>
                    <table class="border-collapse table-auto w-full text-sm">
                        <thead>
                        <tr>
                            <th class="border-b font-medium p-4 pl-8 pt-0 pb-3 text-gray-400 text-left">Company</th>
                            <th class="border-b font-medium p-4 pt-0 pb-3 text-gray-400 text-left">Logo</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Email</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Total employees</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Edit</th>
                        </tr>
                        </thead>
                        <tbody class="bg-white">
                        @foreach($companies as $company)
                            <tr>
                                <td class="border-b border-gray-100 p-4 pl-8 text-gray-500">{{ $company->name }}</td>
                                <td class="border-b border-gray-100 p-4 text-gray-500">
                                    @if($company->logo) <img src="{{ '/logos/'.$company->logo }}" alt="{{ $company->name }} logo" style="max-width: 100px"> @endif
                                </td>
                                <td class="border-b border-gray-100 p-4 pr-8 text-gray-500">{{ $company->email }}</td>
                                <td class="border-b border-gray-100 p-4 pr-8 text-gray-500">
                                    <a href="{{ @route('company.employees', $company->id) }}">{{ $company->employees()?->count() }}</a>
                                </td>
                                <td class="border-b border-gray-100 p-4 pr-8 text-gray-500">
                                    <a href="{{ @route('company.edit', $company->id) }}"><i class="fa fa-edit"></i></a>
                                    <a href="#" class="delete" data-name="{{ $company->name }} ({{ $company->id }})" data-id="{{ $company->id }}"><i class="fa fa-trash"></i></a>
                                    <form action="{{ @route('company.destroy', $company->id) }}" method="post" id="{{ $company->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" style="display: none">
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employee-create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            <span class="text-gray-800">{{ __('Create employee') }}</span>
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-1 gap-6">
                        <form method="post" action="{{ @route('employee.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('partials.employee-form')
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/employee-edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            <span class="text-gray-800">{{ $employee->firstname }} {{ $employee->lastname }}</span><i class="fa fa-edit text-gray-400 ml-2"></i>
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-1 gap-6">
                        <form method="post" action="{{ @route('employee.update', $employee->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            @include('partials.employee-form')
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/employee.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            @if(!empty($company)) {{ $company->name }} - @endif {{ __('Employees') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="@if(!empty($company)){{ @route('company.employee.create', $company->id) }} @else {{ @route('employee.create') }} @endif" class="float-right">
                        <i class="fa fa-plus-circle"></i>
                    </a>

                    <table class="border-collapse table-auto w-full text-sm">
                        <thead>
                        <tr>
                            <th class="border-b font-medium p-4 pl-8 pt-0 pb-3 text-gray-400 text-left">Name</th>
                            <th class="border-b font-medium p-4 pt-0 pb-3 text-gray-400 text-left">Company</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Email</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Phone</th>
                            <th class="border-b font-medium p-4 pr-8 pt-0 pb-3 text-gray-400 text-left">Edit</th>
                        </tr>
                        </thead>
                        <tbody class="bg-white">
                        @foreach($employees as $employee)
                            <tr>
                                <td class="border-b border-gray-100 p-4 pl-8 text-gray-500">{{ $employee->firstname }} {{ $employee->lastname }}</td>
                                <td class="border-b border-gray-100 p-4 text-gray-500">{{ $employee->company()?->name }}</td>
                                <td class="border-b border-gray-100 p-4 text-gray-500">{{ $employee->email }}</td>
                                <td class="border-b border-gray-100 p-4 pr-8 text-gray-500">{{ $employee->phone }}</td>
                                <td class="border-b border-gray-100 p-4 pr-8 text-gray-500">
                                    <a href="{{ @route('employee.edit', $employee->id) }}"><i class="fa fa-edit"></i></a>
                                    <a href="#"
                                       class="delete"
                                       data-name="{{ $employee->firstname }} {{ $employee->lastname }} ({{ $employee->id }})"
                                       data-id="{{ $employee->id }}"
                                    >
                                        <i class="fa fa-trash"></i>
                                    </a>
                                    <form action="{{ @route('employee.destroy', $employee->id) }}" method="post" id="{{ $employee->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" style="display: none">
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>